spring:
  application:
    name: sharding-jdbc-demo
  shardingsphere:
    #水平分库，配置三个数据源
    datasource:
      names: m1,m2,m0
      m0:
        type: com.zaxxer.hikari.HikariDataSource
        dirver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
        max-active: 16
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        dirver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/edu_db_1?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
        max-active: 16
      m2:
        type: com.zaxxer.hikari.HikariDataSource
        dirver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/edu_db_2?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
        max-active: 16
    sharding:
      broadcast-tables: t_udict
      tables:
        # 公共表
        t_udict:
          key-generator:
            column: dictid
            type: SNOWFLAKE
        # 表的规则，表明都是course1、course2，以course开头
        t_user:
          actual-data-nodes: m$->{0}.t_user
          key-generator:
            column: user_id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: t_user
        course:
          # 行表达式标识符，如果是三个表，就是 tableName$->{1..3}
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
          # 指定course表里面主键生成的策略：snowflake 雪花算法
          key-generator:
            column: cid
            type: SNOWFLAKE
          # 指定分片策略 约定cid值是奇数，添加course2，cid值是偶数，添加course1
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: course_$->{cid % 2 + 1}

          # 指定数据库分片策略 约定user_id值是奇数，添加m2，user_id值是偶数，添加m1
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: m$->{user_id % 2 + 1}

      props:
        sql:
          show: true

  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  type-aliases-package: com.xtt.shardingjdbcdemo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false